DROP TABLE FACEBOOK_EVENT;
DROP TABLE TWITTER_TWEET;

CREATE TABLE FACEBOOK_EVENT(ID INTERGER PRIMARY KEY AUTOINCREMENT, NAME VARCHAR(255), DESCRIPTION VARCHAR(255), EVENT_ID VARCHAR(50), STARTTIME DATE, DATE_ID VARCHAR(12));
CREATE TABLE TWITTER_TWEET(ID INTERGER PRIMARY KEY AUTOINCREMENT, TEXT VARCHAR(150), TWEET_ID VARCHAR(50), CREATEDAT DATE, DATE_ID VARCHAR(12));